### ISSUE TITLE
Ajouter middleware isCaptain pour refuser une candidature à une équipe

### ISSUE THREAD

**Issue by Fleuh** [ungdev/UA-api#105]
https://github.com/ungdev/UA-api/blob/71c3479363bfb0d10a800e026338c13f3896ab64/src/api/controllers/team/refuse.js#L17

**Comment by florianess** [comment]
C'est aussi utilisé pour un user qui a demandé de rejoindre la team et qui veux annuler ça demander. Y a moyen de faire un OU dans un middleware. Du style (isCaptain() || isAskingTeam() )
