### ISSUE TITLE
Gestion des refresh token

### ISSUE THREAD

**Issue by ValentinPeltier** [ungdev/UA-api#47]
Les refresh token permettent à l'utilisateur de devoir uniquement renvoyer son refresh token pour renouveler son login token sans avoir à se reconnecter

**Comment by nyc4m** [comment]
@florianess finalement on vire cette fonctionnalité ou pas ?

**Comment by arnaud9145** [comment]
Une manière simple de le faire sinon est de renvoyer un token à l'utilisateur fréquemment, par exemple lorsqu'il requête ses infos

**Comment by arnaud9145** [comment]
Mais un vrai refresh token reste mieux

**Comment by ValentinPeltier** [comment]
Fonctionnalité annulée
