### ISSUE TITLE
Mettre à jour le controller Team

### ISSUE THREAD

**Issue by florianess** [ungdev/UA-api#57]
Réadapter le controller Team pour le rendre Restful

- [x] GET teams/ (toutes les teams)

- [x] GET teams/:id (team specific)

- [x] POST teams/ (ajouter une team)

- [x] PUT teams/:id (modifier une team) A FAIRE ?????

- [x] DELETE teams/:id (supprimer une team)

- [x] POST teams/:teamId/users (accepter un user dans la team/ajouter un user en tant qu'admin)

- [x] POST teams/:teamId/request (user crée une demande de join à une équipe)

- [x] DELETE teams/:teamId/request (user annule sa demande de join à une équipe)

- [x] DELETE teams/:teamId/users/:userId (leave une team/kick un joueur/refuser un joueur)

**Comment by ThomasLachaux** [comment]
Ref utiles:
https://blog.octo.com/designer-une-api-rest/
https://softwareengineering.stackexchange.com/questions/141410/restful-state-changing-actions
https://blog.florimond.dev/restful-api-design-13-best-practices-to-make-your-users-happy
