### ISSUE TITLE
Revoir le système de permissions

### ISSUE THREAD

**Issue by florianess** [ungdev/UA-api#61]
- [ ] Rendre fonctionnel le système de permissions avec une hiérarchie (admin > respo > captain > self > user)
- [ ] Protéger les routes via les permissions
- [ ] Déprécier les routes admin

**Comment by nyc4m** [comment]
@florianess pour le coup je pense qu'il faudrait faire la #66 avant celle-çi

**Comment by nyc4m** [comment]
@ValentinPeltier Il me semble que tu as faite celle là finalement non ?

**Comment by ValentinPeltier** [comment]
@nyc4m c'est fait
