### ISSUE TITLE
Saler les mots de passe

### ISSUE THREAD

**Issue by ThomasLachaux** [ungdev/UA-api#64]
[https://www.youtube.com/watch?v=8ZtInClXe1Q](https://www.youtube.com/watch?v=8ZtInClXe1Q), cette vidéo c'est le feu

**Comment by nyc4m** [comment]
Les mots de passes sont déjà salés d'après ce que j'ai vu :eyes:

**Comment by ThomasLachaux** [comment]
Ah ! ^^
Oui, je viens de comprendre, avec ARENA_API_BCRYPT_LEVEL=11

Autant pour moi 😅
