### ISSUE TITLE
Séparer les routes des contrôleurs 

### ISSUE THREAD

**Issue by ThomasLachaux** [ungdev/UA-api#66]
Séparer les routes des contrôleurs pour avoir un meilleur modèle MVC.

ça sera sûrement plus facile après pour gérer les permissions

La structure serait donc
- Controllers
	user/
		blabla.js
	auth/
		blabla.js
-Routes
	user.js
	auth.js

A voir si on réunit toutes les routes en un fichier ou sépare

A voir aussi si c'est vraiment intéressant #Google #StackOverflow

liste des modules à traiter : 
- [x] cart
- [x] cartItems
- [x] network
- [x] items 
- [X] auth
- [x] team
- [x] tournament
- [x] user

**Comment by nyc4m** [comment]
On peut aussi passer en [ADR](https://en.wikipedia.org/wiki/Action%E2%80%93domain%E2%80%93responder) au lieu du MVC, askip c'est mieux :thinking:

**Comment by Fleuh** [comment]
En réalité, on n'est déjà plus en MVC vu qu'on utilise Redux, qui est lui même une implémentation de l'architecture Flux (qui elle même se rapproche de ADR).

**Comment by Fleuh** [comment]
Pour ceux qui ont les notifs j'ai delete, j'avais pas vu que c'était l'API my bad :p
